name: a_star
description: A sample A* algorithm built with Dart.
homepage: https://github.com/sethladd/dart-a-star
version: 0.5.0-dev

environment:
  sdk: '>=2.8.1 <3.0.0'

dev_dependencies:
  benchmark_harness: any
  test: any
